--Update join needed for one of the SQL jobs
UPDATE a
SET a.EVT_TARGET = b.CRT_ESTIMATEDISSUEDATE
	,a.EVT_SCHEDEND = b.CRT_ESTIMATEDRETURNDATE
FROM R5EVENTS a
JOIN R5CUSTOMERRENTALS b ON a.EVT_UDFCHAR41 = b.CRT_CODE

UPDATE R5CUSTOMERRENTALS
SET CRT_INSTRUCTION1 = (
		SELECT Stuff((
					SELECT ' ' + EVT_CODE + ' - ' + SUBSTRING(EVT_DESC, 1, 11) + ','
					FROM R5EVENTS
					WHERE EVT_UDFCHAR41 = CRT_CODE
					FOR XML path('')
					), 1, 1, '')
		)

