--List of stock for the purpose of yearly inventory
SELECT
PAR_CODE Komponent
,PAR_DESC Nazwa
,ISNULL(PAR_LONGDESCRIPTION, '') Opis
,ISNULL(PAR_UDFCHAR12, '') StadlerID
,ISNULL(PAR_UDFCHAR06, '') ArtikelNr
,ISNULL(PAR_UDFCHAR02, '') Typ
,ISNULL(PAR_PREFSUP, '') PreferowanyDostawca
,PAR_UOM Jednostka
,ISNULL(PPR_AVGPRICE,0) CenaZaJednostkę
,SUM(ISNULL(BIS_QTY, 0)) IlośćSprawnychCzęści
,SUM(ISNULL(BIS_REPAIRQTY, 0)) IlośćUszkodzonychCzęści
,SUM(ISNULL(BIS_QTY, 0)) + SUM(ISNULL(BIS_REPAIRQTY, 0)) IlośćCałkowita
,SUM(ISNULL(BIS_QTY, 0)) * ISNULL(PPR_AVGPRICE,0) WartośćCałkowita
,STO_STORE Magazyn
,STR_ORG OrganizacjaMagazynu
FROM R5PARTS
JOIN R5STOCK ON STO_PART = PAR_CODE AND STO_PART_ORG = PAR_ORG
JOIN R5STORES ON STR_CODE = STO_STORE
JOIN R5BINSTOCK ON BIS_PART = PAR_CODE AND BIS_PART_ORG = PAR_ORG AND STO_STORE = BIS_STORE
LEFT JOIN R5PARTPRICES ON PPR_PART = PAR_CODE AND PPR_PART_ORG = PAR_ORG AND PPR_ORG = STR_ORG
where STR_ORG ='PL3' and PAR_NOTUSED='+'
GROUP BY
STO_STORE,
PAR_CODE, PAR_DESC, PAR_LONGDESCRIPTION, PAR_UDFCHAR12, PAR_UDFCHAR06, PAR_UDFCHAR02, PAR_UOM
, PPR_AVGPRICE, STR_ORG
, PAR_PREFSUP
order by STR_ORG asc




















































